# Generated by Django 2.2.13 on 2020-08-04 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(choices=[('SINGER', 'SINGER'), ('ACTOR', 'ACTOR'), ('TALENT', 'TALENT'), ('DIRECTOR', 'DIRECTOR')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='관광지 이름', max_length=100, verbose_name='관광지 이름')),
                ('content', models.TextField(blank=True, verbose_name='관광지 태그')),
                ('address', models.CharField(help_text='광관지 주소', max_length=150, verbose_name='관광지 주소')),
                ('average_score', models.PositiveIntegerField(default=0, help_text='평균점수')),
                ('phone_number', models.CharField(help_text='관광지 전화번호', max_length=100)),
                ('open_time', models.CharField(help_text='관광지 오픈 시간', max_length=100)),
                ('url', models.URLField(help_text='관광지 관련 URL')),
                ('trans', models.CharField(help_text='관광지 교통편', max_length=255)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='후기 타이들', max_length=100)),
                ('content', models.TextField(help_text='후기 내용')),
                ('evaluated_score', models.PositiveSmallIntegerField(default=0, help_text='관광지 평가 점수')),
                ('release_date', models.DateTimeField(auto_now_add=True, help_text='후기 생성된 시간')),
                ('place', models.ForeignKey(help_text='리뷰 관련 관광지', on_delete=django.db.models.deletion.CASCADE, to='tours.Place')),
                ('user', models.ForeignKey(help_text='후기 작성자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='태그명')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=20)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.PlaceReview')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(help_text='관광지 태그 목록', to='tours.Tag', verbose_name='해시태그 목록'),
        ),
        migrations.CreateModel(
            name='KPopContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('mv', '영화'), ('mu', '음악'), ('tv', '방송'), ('kc', '문화'), ('cb', '셀럽'), ('gp', '그룹')], default='kc', max_length=2, verbose_name='타입')),
                ('title', models.CharField(max_length=100, verbose_name='컨텐츠 제목')),
                ('celebrity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Celebrity')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpopcategories', to='tours.Place')),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Celebrity')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Place')),
            ],
        ),
    ]
