# Generated by Django 2.2.12 on 2020-07-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpopcategory',
            name='content_type',
        ),
        migrations.AddField(
            model_name='kpopcontent',
            name='content_type',
            field=models.CharField(choices=[('mv', '영화'), ('mu', '음악'), ('tv', '방송'), ('kc', '문화'), ('cb', '셀럽'), ('gp', '그룹')], default='kc', max_length=2, verbose_name='타입'),
        ),
    ]
