# Generated by Django 2.2.12 on 2020-07-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(help_text='관광지 태그 목록', to='tours.Tag', verbose_name='해시태그 목록'),
        ),
    ]
