# Generated by Django 2.2.12 on 2020-07-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20200721_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='profession',
            field=models.CharField(choices=[('SINGER', 'SINGER'), ('ACTOR', 'ACTOR'), ('TALENT', 'TALENT'), ('DIRECTOR', 'DIRECTOR')], max_length=20),
        ),
    ]
