# Generated by Django 2.2.12 on 2020-07-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20200721_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpopcategory',
            name='kpop_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpopcategories', to='tours.KPopContent'),
        ),
        migrations.AlterField(
            model_name='kpopcategory',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpopcategories', to='tours.Place'),
        ),
    ]
